### ISSUE TITLE
Checking for updates start a new alfred instance

### ISSUE THREAD

**Issue by jondeodat** [SamVerschueren/alfred-updater#4]
Do you guys hit the same issue when alfred-updater runs?
On my mac, it creates a second instance (and a third etc every time it runs). 
I'm on macOS Mojave 10.14.3 with node 11.10.1 and alfred latest version 3.8.1.
The bug was there for quite some time but I just discovered alfred-updater is responsible. 
Is there something to configure?
Thx.

Demo: https://drive.google.com/open?id=1xAU0JnquOb93_6ESCyQqR-OGZww9Kl-U

**Comment by SamVerschueren** [comment]
This should be fixed right now. The reason I have to re-open Alfred is to make sure it reloads all the workflows again. This is now done by killing the application first and then re-opening it.
