### ISSUE TITLE
Doesn't work with Alfred 4

### ISSUE THREAD

**Issue by askhogan** [SamVerschueren/alfred-updater#5]

**Comment by duncup** [comment]
Got this too.

**Comment by vysinsky** [comment]
I saw a new version of https://github.com/SamVerschueren/resolve-alfred-prefs was released. Do you plan to upgrade alfred-updater, please?

**Comment by jkaan** [comment]
Same here!

**Comment by PingWeb** [comment]
Still does not work

**Comment by SamVerschueren** [comment]
I'm working on this right now. Hope to get this out tomorrow.

**Comment by SamVerschueren** [comment]
Updated the workflow and it should work for Alfred 4 now. Feel free to open an issue if you find something.
